title: Open Policy Agent for dotnet core
description: SDK for using WebAssembly (wasm) compiled Open Policy Agent Rego policies with dotnet core
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme