name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/v*'
    paths:
      - 'src/**'
      - '.github/workflows/code-quality.yaml'

jobs:
  native_build:
    uses: ./.github/workflows/opa-native.yaml

  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: 'Qodana Setup'
        shell: pwsh
        run: ./build/qodana.ps1 -SkipScan

      - name: get_opa_lib
        uses: actions/download-artifact@v4
        with:
          name: opa-native
          path: ./src/Compilation/Interop/lib

      - name: Build
        run: dotnet build -c Release ./qodana.sln

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --no-build
          #args: --solution,./qodana.sln,--linter,jetbrains/qodana-cdnet,--configuration,Release
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
