name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/v*'
    paths:
      - 'src/**'
      - '.github/workflows/code-quality.yaml'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Setup'
        shell: pwsh
        run: ./build/qodana.ps1 -SkipScan

      - name: get_opa_lib
        uses: actions/download-artifact@v4
        with:
          name: opa-native
          path: ./src/Compilation/Interop/lib

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          #args: --solution,./qodana.sln,--linter,jetbrains/qodana-cdnet,--configuration,Release
          cache-default-branch-only: true
