name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/v*'
    paths:
      - 'src/**'
      - '.github/workflows/code-quality.yml'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Qodana Scan'
        shell: pwsh
        run: ./build.ps1 -Token $QODANA_TOKEN -Image 'jetbrains/qodana-cdnet:2023.3-eap'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
