name: docs

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #    - 'docs/**'
  #    - 'src/**'
  #    - '.github/workflows/docs.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'docs/**'
  #     - 'src/**'
  #     - '.github/workflows/docs.yml'
  workflow_dispatch:
    inputs:
      release:
        description: Publish documentation
        required: false
        type: boolean

jobs:
  native_build:
    uses: ./.github/workflows/opa-native.yaml

  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Get Version
      id: get_version
      run: |
        echo "version=$(dotnet nbgv get-version -v NuGetPackageVersion)" >> "$GITHUB_OUTPUT"

    - name: get_opa_lib
      uses: actions/download-artifact@v4
      with:
        name: opa-native
        path: ./src/Compilation/Interop/lib

    - run: dotnet build -f net8.0 ./docs/snippets/Snippets.csproj
    - run: dotnet tool update -g docfx
    - run: docfx docs/docfx.json --metadata _appTitle="OpaDotNet ${{ steps.get_version.outputs.version }}"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ inputs.release }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
