name: docs

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #    - 'docs/**'
  #    - 'src/**'
  #    - '.github/workflows/docs.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'docs/**'
  #     - 'src/**'
  #     - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - run: dotnet build -f net8.0 ./docs/snippets/Snippets.csproj
    - run: dotnet tool update -g docfx
    - run: docfx docs/docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
